[build-system]
requires = [
    "dask",
    "numba==0.56.0",
    "numpy",
    "ome_types",
    "opencv_python",
    "pandas",
    "pydantic",
    "scikit_image==0.18.3",
    "scikit_learn==1.1.3",
    "scipy==1.8.0",
    "setuptools==49.2.1",
    "tifffile==2022.2.2"
]
build-backend = "setuptools.build_meta"